version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
        environment: &ENVIRONMENT
          DOCKER_IMAGE_NAME: decentraland/communications-server


    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker: { docker_layer_caching: true }

      - run:
          name: Build Docker image
          command: docker build -t $DOCKER_IMAGE_NAME:$CIRCLE_SHA1 .

      - run:
          name: Run test
          command: docker run --rm $DOCKER_IMAGE_NAME:$CIRCLE_SHA1 make test

      - run:
          name: Log in DockerHub
          command: docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"

      - run:
          name: Push image
          command: |
            if echo "$CIRCLE_BRANCH" | grep "^master$"; then
              docker tag "$DOCKER_IMAGE_NAME:$CIRCLE_SHA1" "$DOCKER_IMAGE_NAME:$CIRCLE_BRANCH"
              docker push "$DOCKER_IMAGE_NAME:$CIRCLE_SHA1"
            elif echo "$CIRCLE_BRANCH" | grep "^dev$"; then
              docker tag "$DOCKER_IMAGE_NAME:$CIRCLE_SHA1" "$DOCKER_IMAGE_NAME:$CIRCLE_BRANCH"
              docker push "$DOCKER_IMAGE_NAME:$CIRCLE_SHA1"
            elif echo "$CIRCLE_TAG" | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+$"; then
              docker tag "$DOCKER_IMAGE_NAME:$CIRCLE_SHA1" "$DOCKER_IMAGE_NAME:$CIRCLE_TAG"
              docker push "$DOCKER_IMAGE_NAME:$CIRCLE_TAG"
            else
              echo "Not a release, skipping push"
            fi

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
